name: firebase_app_installations_platform_interface
description: A common platform interface for the firebase_app_installations plugin.
version: 0.1.1+16
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_app_installations/firebase_app_installations_platform_interface
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_app_installations/firebase_app_installations_platform_interface

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  firebase_core_platform_interface: ^4.5.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
