name: firebase_auth_web
description: The web implementation of firebase_auth
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth_web
version: 4.4.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"

dependencies:
  firebase_auth_platform_interface: ^6.8.0
  firebase_core: ^1.10.0
  firebase_core_web: ^1.7.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http_parser: ^4.0.0
  intl: ^0.17.0
  js: ^0.6.3
  meta: ^1.3.0

dev_dependencies:
  firebase_auth:
    path: ../firebase_auth
  firebase_core_platform_interface: ^4.5.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAuthWeb
        fileName: firebase_auth_web.dart
