name: firebase_performance
description:
  Flutter plugin for Google Performance Monitoring for Firebase, an app
  measurement solution that monitors traces and HTTP/S network requests on Android and
  iOS.
homepage: https://firebase.google.com/docs/perf-mon
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_performance/firebase_performance
version: 0.8.3

false_secrets:
  - example/**

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core: ^1.10.0
  firebase_core_platform_interface: ^4.5.1
  firebase_performance_platform_interface: ^0.1.1+16
  firebase_performance_web: ^0.1.1+5
  flutter:
    sdk: flutter

dev_dependencies:
  e2e: ^0.6.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  http: ^0.13.0
  mockito: ^5.0.0
  pedantic: ^1.8.0
  plugin_platform_interface: ^2.0.0
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.performance
        pluginClass: FlutterFirebasePerformancePlugin
      ios:
        pluginClass: FLTFirebasePerformancePlugin
      web:
        default_package: firebase_performance_web
