name: firebase_dynamic_links
description:
  Flutter plugin for Google Dynamic Links for Firebase, an app solution for creating
  and handling links across multiple platforms.
version: 4.3.7
homepage: https://firebase.google.com/docs/dynamic-links
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_dynamic_links

false_secrets:
  - example/**

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core: ^1.10.0
  firebase_core_platform_interface: ^4.5.1
  firebase_dynamic_links_platform_interface: ^0.2.3+12
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.dynamiclinks
        pluginClass: FlutterFirebaseDynamicLinksPlugin
      ios:
        pluginClass: FLTFirebaseDynamicLinksPlugin
