name: firebase_ml_model_downloader
description: A Flutter plugin allowing you to use Firebase Ml Model Downloader.
version: 0.1.1+7
homepage: https://firebase.google.com/docs/ml/flutter/use-custom-models
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_ml_model_downloader/firebase_ml_model_downloader

false_secrets:
  - example/**

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  firebase_core: ^1.10.0
  firebase_core_platform_interface: ^4.5.1
  firebase_ml_model_downloader_platform_interface: ^0.1.1+16
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.firebase_ml_model_downloader
        pluginClass: FirebaseModelDownloaderPlugin
      ios:
        pluginClass: FirebaseModelDownloaderPlugin
      macos:
        pluginClass: FirebaseModelDownloaderPlugin
