# FlutterFire_X naming due to package being take already on Pub.dev.
name: firebase_app_installations
description: A Flutter plugin allowing you to use Firebase Installations.
version: 0.1.1+7
homepage: https://firebase.google.com/docs/projects/manage-installations#flutter
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_app_installations/firebase_app_installations

false_secrets:
  - example/**

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  firebase_app_installations_platform_interface: ^0.1.1+16
  firebase_app_installations_web: ^0.1.1+5
  firebase_core: ^1.10.0
  firebase_core_platform_interface: ^4.5.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  plugin_platform_interface: ^2.0.0
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.installations.firebase_app_installations
        pluginClass: FirebaseInstallationsPlugin
      ios:
        pluginClass: FirebaseInstallationsPlugin
      macos:
        pluginClass: FirebaseInstallationsPlugin
