name: firebase_app_installations_web
description: The web implementation of firebase_app_installations.
version: 0.1.1+5
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_app_installations/firebase_app_installations_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_app_installations/firebase_app_installations_web

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  firebase_app_installations_platform_interface: ^0.1.1+16
  firebase_core: ^1.10.0
  firebase_core_web: ^1.7.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  firebase_core_platform_interface: ^4.5.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAppInstallationsWeb
        fileName: firebase_app_installations_web.dart
