name: firebase_database
description: Flutter plugin for Firebase Database, a cloud-hosted NoSQL database
  with realtime data syncing across Android and iOS clients, and offline access.
homepage: https://firebase.google.com/docs/database
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_database/firebase_database
version: 9.1.4

false_secrets:
 - example/**

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core: ^1.10.0
  firebase_core_platform_interface: ^4.5.1
  firebase_database_platform_interface: ^0.2.2+4
  firebase_database_web: ^0.2.1+6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.2
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.database
        pluginClass: FirebaseDatabasePlugin
      ios:
        pluginClass: FLTFirebaseDatabasePlugin
      macos:
        pluginClass: FLTFirebaseDatabasePlugin
      web:
        default_package: firebase_database_web
