name: firebase_dynamic_links_platform_interface
description: A common platform interface for the firebase_dynamic_links plugin.
version: 0.2.3+12
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_dynamic_links/firebase_dynamic_links_platform_interface
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_dynamic_links/firebase_dynamic_links_platform_interface

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.5"

dependencies:
  firebase_core: ^1.10.3
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0


dev_dependencies:
  firebase_core_platform_interface: ^4.5.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
